# Use uma imagem oficial do Nginx
FROM nginx:alpine

# Copia a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos da aplicação frontend para o diretório padrão do Nginx
COPY . /usr/share/nginx/html