services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/share/nginx/html
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MONGO_URL=mongodb://db:27017/libreflix
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: